---
images:
  - name: RHEL-96-el-amd64-minimal
    distribution: rhel-9
    description: RHEL 9.latest image customized for OCP4 on Hetzner
    customizations:
      kernel:
        append: rd.auto
      partitioning_mode: lvm
      packages:
        - lvm2
        - mdadm
        - bzip2
      filesystem:
        - mountpoint: /boot
          min_size: 1024
        - mountpoint: /
          min_size: 10240
